apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - flux/image-repository.yaml
  - flux/image-policy.yaml
  - flux/image-update-automation.yaml
  - flux/kustomization-keda.yaml
  - flux/kustomization-ingest.yaml
images:
  - name: 404379474987.dkr.ecr.us-east-1.amazonaws.com/glassbox
    newTag: "build-73" # {"$imagepolicy": "flux-system:glassbox:tag"}
