apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 404379474987.dkr.ecr.us-east-1.amazonaws.com/glassbox:latest
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: glassbox-config
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: glassbox-mysql
                  key: mysql-password
            - name: GLASSBOX_IP_HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: glassbox-app
                  key: ip-hash-salt
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              memory: 256Mi
