apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-app.yaml
  - namespace-data.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - configmap-app.yaml
  - migrate-job.yaml
  - rbac-api.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - worker-deployment.yaml
  - warm-cronjob.yaml
  - networkpolicy-data.yaml
  - networkpolicy-app.yaml
